@startuml
actor User
create CLI
User -> CLI ++ : tsv + scanner info
create Scanner
CLI -> Scanner: withInfo()
create Scan2D
CLI -> Scan2D ++: fromTSV()
Scan2D -> Scanner ++ : getInfo
return Info
return points
create NeighborhoodGraph
CLI -> NeighborhoodGraph ++ : fromPoints(points)
return graph
create ModelFitting
CLI -> ModelFitting ++ : fitLines(graph)
return initialisedLines
destroy ModelFitting
create NAPSAC
CLI -> NAPSAC ++ : initialisedLines
note right : To be\nimplemented
return betterLines
destroy NAPSAC

return plot + fittedLines



@enduml
