name: Build&Test
on: [pull_request]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest #, macos-latest, windows-latest
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
      - name: test
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: jacocoTestReport
      - name: codecov
        uses: codecov/codecov-action@v1
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
