name: Release
on:
  push:
    branches:
      - master
      - dev
      - fix-semantic-release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build distribution
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: distZip
      - run: ls
      - name: Print .releaserc.json
        run: cat .releaserc.json
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install semantic-release
        run: npm i -g semantic-release @semantic-release/changelog
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --debug
